const SHOP_REQUESTED = 'SHOP_REQUESTED'
const SHOP_LOADED = 'SHOP_LOADED'
const SHOP_ERROR = 'SHOP_ERROR'
const ADD_TO_CART = 'ADD_TO_CART'
const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export {SHOP_REQUESTED, SHOP_LOADED, SHOP_ERROR, ADD_TO_CART, REMOVE_FROM_CART}